include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - dart_code_metrics

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    source-lines-of-code: 60
    maintainability-index: 50
    number-of-parameters: 3
    number-of-methods: 10
    maximum-nesting-level: 5
  metrics-exclude:
    - test/**
  rules:
    - list_remove_unrelated_type
    - iterable_contains_unrelated_type
    - avoid-duplicate-exports
    - avoid-dynamic:
        exclude:
          - lib/feature/*/data/api/**
          - lib/routing/root_router_delegate.dart
    - avoid-global-state
    - avoid-missing-enum-constant-in-map
    - avoid-nested-conditional-expressions
    - avoid-non-null-assertion
    - avoid-throw-in-catch-block
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - avoid-unrelated-type-assertions
    - avoid-unused-parameters
    - binary-expression-operand-order
    - double-literal-format
    - format-comment
    - member-ordering-extended:
        order:
          - constructors
          - public-fields
          - private-fields
          - factory-constructors
          - public-getters
          - private-getters
          - public-setters
          - private-setters
          - public-methods
          - private-methods
    - newline-before-return:
        severity: style
    - no-boolean-literal-compare
    - no-empty-block:
        severity: warning
    - prefer-trailing-comma:
        severity: style
    - prefer-conditional-expressions
    - no-equal-then-else
    - no-object-declaration
    - prefer-commenting-analyzer-ignores
    - prefer-correct-identifier-length:
        exceptions: [ 'i' ]
    - prefer-correct-type-name
    - prefer-enums-by-name
    - prefer-first
    - prefer-immediate-return
    - prefer-last
    - prefer-match-file-name:
        exclude:
          - test/**
    - prefer-moving-to-variable
    - always-remove-listener
    - avoid-border-all
    - avoid-returning-widgets
    - avoid-shrink-wrap-in-lists
    - avoid-unnecessary-setstate
    - avoid-use-expanded-as-spacer
    - avoid-wrapping-in-padding
    - prefer-const-border-radius
    - prefer-correct-edge-insets-constructor
    - prefer-extracting-callbacks:
        ignored-named-arguments:
          - listener
    - prefer-single-widget-per-file:
        ignore-private-widgets: true
