name: cubit_clean_architecture
description: Cubit - presentation logic. Clean architecture - business logic

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.0.1
  provider: ^6.0.3
  json_annotation: ^4.6.0
  equatable: ^2.0.3
  logger: ^1.1.0
  kiwi: ^4.0.2
  dio: ^4.0.6
  pretty_dio_logger: ^1.2.0-beta-1
  google_fonts: ^3.0.1
  easy_localization: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  dart_code_metrics: ^4.17.0
  build_runner: ^2.2.0
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
