name: cubit_clean_architecture
description: Cubit - presentation logic. Clean architecture - business logic

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc:
  provider:
  json_annotation:
  equatable:
  logger:
  kiwi:
  dio:
  pretty_dio_logger:
  google_fonts:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  dart_code_metrics:
  build_runner:
  json_serializable:

flutter:
  uses-material-design: true
